### ISSUE TITLE
New Game - Human Zero Game

### ISSUE THREAD

**Issue by dastrong** [dastrong/ESLintheROK-front#48]
**Is this a new game idea or a recreation of another game?**
recreation

**Describe your game idea**
- everyone in the class sits down and read the sentence on the screen
- groups of students must decide how many of them stand up
- show a number on the screen and if it matches that group gets a point

**Would you game be played in the browser, printed, or both?**
browser

**Additional context**
- the number should go from 0 to the minimum group size
- have the max number be adjustable, so you can play with the whole class

**Comment by Mr-Baga08** [comment]
I would like to contribute.

**Comment by dastrong** [comment]
How would you like to contribute, design it, code it, both?

**Comment by dastrong** [comment]
> I would like to contribute.

How would you like to contribute, design it, code it, both?
